version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: merxpos-sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: merxpos-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: merxpos-redis
    ports:
      - "6379:6379"